### PR TITLE
refactor: move string handling to stringMsg.js

### PR DESCRIPTION
**Pull request by webmasterkai**
Attempting to organize all parse/encode of sentence strings into a dedicated file.

### CODE REVIEW

**Comment by sbender9** [comment]
Getting:

```
Unable to convert:n2k.timestamp.substring is not a function:{"canId":486494156,"prio":7,"src":204,"dst":255,"pgn":65359,"timestamp":"2019-04-17T12:26:48.827Z","fields":{"Manufacturer Code":"Raymarine","Industry Code":"Marine Industry","Heading Magnetic":1.0406},"description":"Seatalk: Pilot Heading"}
TypeError: Cannot read property 'values' of undefined
    at ToSignalK._transform (/usr/local/src/signalk-server-node.master/node_modules/@signalk/streams/n2k-signalk.js:33:35)
    at ToSignalK.Transform._read (_stream_transform.js:186:10)
    at ToSignalK.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at ToSignalK.Writable.write (_stream_writable.js:290:11)
    at Ydgw02Stream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Ydgw02Stream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
```

**Comment by sbender9** [comment]
```TypeError: n2k.timestamp.substring is not a function
    at toDelta (/usr/local/src/signalk-server-node.master/node_modules/@signalk/n2k-signalk/n2kMapper.js:31:27)
    at ToSignalK._transform (/usr/local/src/signalk-server-node.master/node_modules/@signalk/streams/n2k-signalk.js:32:19)
    at ToSignalK.Transform._read (_stream_transform.js:186:10)
    at ToSignalK.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at ToSignalK.Writable.write (_stream_writable.js:290:11)
    at Ydgw02Stream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Ydgw02Stream.emit (events.js:211:7)
```

**Comment by webmasterkai** [comment]
Thanks for checking this. Do we want to enforce timestamps to be strings instead of date objects within canboatjs or should that conversion happen when it turns into a JSON string? Why does SK server need a substring of a timestamp? I'll add tests for whatever is decided.

**Comment by sbender9** [comment]
We need to keep backwards compatibility. Probably some old left over code when timestamps weren't right from canboat or something.

This never gets turned into a json string, so timestamp needs to be a string since that's what is expected.

**Comment by sbender9** [comment]
Looks like the date format is wrong?

**Comment by sbender9** [comment]
`"timestamp" : "Wed Apr 17T2019 09:39:29 GMT-0400 (EDT)"`

**Comment by sbender9** [comment]
Looks good now. Can you fix the conflicts?

**Comment by webmasterkai** [comment]
Working on the conflicts. I also want to add a test to make sure timestamps are strings.

**Comment by webmasterkai** [comment]
This is working but I'm not convinced I have an accurate test against the timestamps always being strings. I can keep in mind for further refinement.

**Comment by tkurki** [comment]
https://github.com/SignalK/n2k-signalk/blob/c06bde80f6ae9b09f5488598c71e6c3c69c418b2/n2kMapper.js#L31-L33

I think this is from a time when the only source for n2k data was `analyzer` and it did not produce valid timestamps, `T` delimiter was a space. I think we should remove the code forcing T in that spot.

**Comment by sbender9** [comment]
> [edit] Perhaps I can create a new function something like `prepPgn` that removes extra fields and checks timestamp is always an ISOString. Then I can create a function test for it and pass the `pgn` object through `prepPgn` before sending to `emit('pgn', pgn)` or `cb(pgn)`.

I think the extra fields are ok. I don't see any need to remove them?

Since we're checking timestamps in the test, is there really a need to check them at runtime?

**Comment by webmasterkai** [comment]
I was thinking of pulling out my fix within the very long `_parse` function that forces the `toISOString()` on Date objects. That way we have a simple function that guarantees timestamp delivery format to SK. That way we can have one place that formats the timestamp instead of calling `toISOString a bunch of times in different places.

**Comment by sbender9** [comment]
Testing with the iKonvert:

```
Apr 17 19:24:54 homepi signalk-server[14822]: (node:14823) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `data` of 'undefined' or 'null'.
Apr 17 19:24:54 homepi signalk-server[14822]:     at Parser.parseString (/tmp/canboatjs/lib/fromPgn.js:313:35)
Apr 17 19:24:54 homepi signalk-server[14822]:     at Parser.parse (/tmp/canboatjs/lib/fromPgn.js:254:19)
Apr 17 19:24:54 homepi signalk-server[14822]:     at CanboatJs._transform (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/canboatjs.js:62:18)
Apr 17 19:24:54 homepi signalk-server[14822]:     at CanboatJs.Transform._read (_stream_transform.js:186:10)
Apr 17 19:24:54 homepi signalk-server[14822]:     at CanboatJs.Transform._write (_stream_transform.js:174:12)
Apr 17 19:24:54 homepi signalk-server[14822]:     at doWrite (_stream_writable.js:396:12)
Apr 17 19:24:54 homepi signalk-server[14822]:     at writeOrBuffer (_stream_writable.js:382:5)
Apr 17 19:24:54 homepi signalk-server[14822]:     at CanboatJs.Writable.write (_stream_writable.js:290:11)
```

**Comment by webmasterkai** [comment]
Looks like you are using it with string mode output. Do you have a way of capturing the raw iKonvert output so I could use it to feed a test?

**Comment by webmasterkai** [comment]
Do we want to emit an error if we get a junk string or just ignore it? I made a test assuming we want to emit an error.

**Comment by sbender9** [comment]
iKonvert is always strings.

Now seeing this:

```
Apr 17 21:26:50 homepi signalk-server[14971]: Error: Parser not found for input.
Apr 17 21:26:50 homepi signalk-server[14971]:     at notFound (/tmp/canboatjs/lib/stringMsg.js:133:10)
Apr 17 21:26:50 homepi signalk-server[14971]:     at n (/tmp/canboatjs/node_modules/lodash/lodash.min.js:5:89)
Apr 17 21:26:50 homepi signalk-server[14971]:     at /tmp/canboatjs/node_modules/lodash/lodash.min.js:97:428
Apr 17 21:26:50 homepi signalk-server[14971]:     at n (/tmp/canboatjs/node_modules/lodash/lodash.min.js:5:89)
Apr 17 21:26:50 homepi signalk-server[14971]:     at /tmp/canboatjs/node_modules/lodash/lodash.min.js:63:257
Apr 17 21:26:50 homepi signalk-server[14971]:     at Parser.parseString (/tmp/canboatjs/lib/fromPgn.js:313:42)
Apr 17 21:26:50 homepi signalk-server[14971]:     at Parser.parse (/tmp/canboatjs/lib/fromPgn.js:254:19)
Apr 17 21:26:50 homepi signalk-server[14971]:     at CanboatJs._transform (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/canboatjs.js:62:18)
Apr 17 21:26:50 homepi signalk-server[14971]:     at CanboatJs.Transform._read (_stream_transform.js:186:10)
Apr 17 21:26:50 homepi signalk-server[14971]:     at CanboatJs.Transform._write (_stream_transform.js:174:12)
Apr 17 21:26:50 homepi signalk-server[14971]: (node:14973) UnhandledPromiseRejectionWarning: Error: Must specify a valid BitView, ArrayBuffer or Buffer
Apr 17 21:26:50 homepi signalk-server[14971]:     at new BitStream (/tmp/canboatjs/node_modules/bit-buffer/bit-buffer.js:309:9)
Apr 17 21:26:50 homepi signalk-server[14971]:     at Parser.parseString (/tmp/canboatjs/lib/fromPgn.js:320:16)
Apr 17 21:26:50 homepi signalk-server[14971]:     at Parser.parse (/tmp/canboatjs/lib/fromPgn.js:254:19)
Apr 17 21:26:50 homepi signalk-server[14971]:     at CanboatJs._transform (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/canboatjs.js:62:18)
Apr 17 21:26:50 homepi signalk-server[14971]:     at CanboatJs.Transform._read (_stream_transform.js:186:10)
Apr 17 21:26:50 homepi signalk-server[14971]:     at CanboatJs.Transform._write (_stream_transform.js:174:12)
Apr 17 21:26:50 homepi signalk-server[14971]:     at doWrite (_stream_writable.js:396:12)
Apr 17 21:26:50 homepi signalk-server[14971]:     at writeOrBuffer (_stream_writable.js:382:5)
Apr 17 21:26:50 homepi signalk-server[14971]:     at CanboatJs.Writable.write (_stream_writable.js:290:11)
Apr 17 21:26:50 homepi signalk-server[14971]:     at iKonvertStream.ondata (_stream_readable.js:639:20)
```

**Comment by sbender9** [comment]
Oh, need to return after emitting the error, but still truing to figure out why...

**Comment by webmasterkai** [comment]
## $PDGY

Sometimes the strings start with `$PDGY` instead of `!PDGY`...
`$PDGY,000000,,,,,,,<CR><LF>`
`$PDGY,000000,4,,5,482,1,0`
`$PDGY,000000,3,,5,484,1,0`
`$PDGY,000000,3,,5,486,1,0`

## [Network Status Sentence](https://github.com/digitalyacht/iKonvert/wiki/4.-Serial-Protocol#3---network-status-sentence)

Provides data about the n2k network at 1-2Hz irrespective of traffic/activity.

$PDGY,{pgn},{load},{errs},{devs},{time},{addr},{rejs}<CR><LF>

- **load** = Bus Load between 0-99%
- **errs** = Frame Errors (not currently supported)
- **devs** = Number of Devices Live on network
- **time** = Network Uptime in seconds
- **addr** = Gateway's CAN address
- **rejs** = Number of Rejected TX PGN Requests

NOTE - Using 000000 PGN here to signify debug/status. 0x0 Should never be seen on the n2k network. 

"Rejected TX PGN Requests" counter increments by 1 each time the application tries to transmit a PGN at a rate faster than the default/recommended update rate as defined by the NMEA2000 Appendix B. For instance, if the application tries to send compass heading at 12Hz the count will increase by two every second as the default/recommended update rate is 10Hz.

## What to do with it?
Do we just ignore it for now? It's useful information.

**Comment by sbender9** [comment]
Let's ignore it for now

**Comment by sbender9** [comment]
I think we're good to merge?

**Comment by webmasterkai** [comment]
Yep. Ready as far as I know.

**Pull request merged**
